project:
  type: website
  output-dir: docs

website:
  title: "🎀 Algoritmos Chic & Pink 🎀"
  navbar:
    left:
      - href: index.qmd
        text: Introducción
      - about.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

